project:
  type: website
  output-dir: docs

website:
  title: "Get Started with REDCap"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Templates

format:
  html:
    theme: journal
    #theme: [cosmo, custom.scss]
    #toc: true



